### ISSUE TITLE
Strange horizontal lines displayed on zoom

### ISSUE THREAD

**Issue by cmccar** [chartjs/chartjs-plugin-zoom#103]
I am plotting a few series of data with a time based x-axis and a numerical based y-axis.

The chart appears as such prior to any zooming:
![image](https://user-images.githubusercontent.com/8409731/30298326-f2a86318-9718-11e7-98f8-94f735d72f91.png)

However, upon zooming into a particular section, I often then see strange erroneous horizontal lines within the chart such as pictured here:
![image](https://user-images.githubusercontent.com/8409731/30298370-159e76aa-9719-11e7-934c-dab4a732ad51.png)

This is the code I use to create and configure the chart (using a screen grab because the "Insert code" functionality seems to remove all the line endings and formatting from my Javascript when I preview the post):
![image](https://user-images.githubusercontent.com/8409731/30298519-a6c712e0-9719-11e7-91f6-334f8eadd03f.png)

If anyone has an idea as to what may be happening, I would greatly appreciate some insight!

**Comment by timKnodel** [comment]
I see the same behavior, but only with Chrome.  Edge and Firefox do not have the same behavior.

**Comment by timKnodel** [comment]
Setting the datasets boarderWidth to anything other than 1 fixed the issue for me.

**Comment by cmccar** [comment]
Ah okay, thanks I appreciate your insight.

I am currently on vacation, but will definitely try changing the borderWidth property to a different number when I'm back and see if that resolves it.

**Comment by BorisVanin** [comment]
timKnodel , thank you so much! I was looked a solution for that artifact lines for 2 years!!! I use Electron so I forced to use Chrome engine. Now I set borderWidth to 1.1 and horizontal lines disappear. Just curious, how did you find a reason?

**Comment by heshamfathi** [comment]
@timKnodel  I had the same issue and solved it by setting boarderWidth  to 2 or anything but 1 and it worked, thanks a ton.

**Comment by joeboe17** [comment]
Changing borderWidth did not seem to help me, but I found more workarounds. The bug stops when you change the cubicInterpolationMode from 'default' to 'monotone' or if you set lineTension to 0.

**Comment by nagix** [comment]
The cause of the issue was in bezier control points off the chart, and this has been fixed in chartjs/Chart.js#5937.

**Comment by TCB13** [comment]
I'm running 4.4.8 and I see this issue as well. Not really sure if with was the same bug or not.

![Image](https://github.com/user-attachments/assets/c374b64f-1f9b-4415-97f5-6ba0c1accf36)

Setting borderWidth to 2 doesn't solve it. It appears randomly.

**Comment by TCB13** [comment]
> I'm running 4.4.8 and I see this issue as well. Not really sure if with was the same bug or not.
> 
> ![Image](https://github.com/user-attachments/assets/c374b64f-1f9b-4415-97f5-6ba0c1accf36)
> 
> Setting borderWidth to 2 doesn't solve it. It appears randomly.

Found the problem. My X axis are date time strings in "SQL format" and [apparently one has to import a date adapter](https://www.chartjs.org/docs/latest/axes/cartesian/time.html) and a 3rd party library to deal with those.

This is a small vanillaJS page so:

```html
<script src="assets/moment.min.js"></script>
<script src="assets/chartjs/chartjs.js" type="text/javascript"></script>
<script src="assets/chartjs/chartjs-plugin-annotation.js" type="text/javascript"></script>
<script src="assets/chartjs/chartjs-adapter-moment.min.js"></script>
```

```js
new Chart(ctx, {
    type: 'line',
    data: {
        datasets: []
    },
    options: {
      scales: {
              x: {
                  type: "time",
                  time: {
                      tooltipFormat: 'HH:mm:ss',
                      unit: "hour",
                      displayFormats: {
                          "hour": "HH"
  
```

Note that I wasn't able to use day.js because the [adapter is only packaged as a ESM module](https://www.jsdelivr.com/package/npm/chartjs-adapter-dayjs-4).
